"""Canonical mapping from public sync SDK methods to CLI commands."""

from __future__ import annotations

METHOD_TO_COMMAND = {
    "DifyClient.message_feedback": "message-feedback",
    "DifyClient.get_application_parameters": "app parameters",
    "DifyClient.file_upload": "files upload",
    "DifyClient.text_to_audio": "text-to-audio",
    "DifyClient.get_meta": "app meta",
    "DifyClient.get_app_info": "app info",
    "DifyClient.get_app_site_info": "app site-info",
    "DifyClient.get_file_preview": "files preview",
    "DifyClient.get_app_site_config": "app site-config get",
    "DifyClient.update_app_site_config": "app site-config update",
    "DifyClient.get_app_api_tokens": "app api-tokens list",
    "DifyClient.create_app_api_token": "app api-tokens create",
    "DifyClient.delete_app_api_token": "app api-tokens delete",
    "CompletionClient.create_completion_message": "completion send",
    "ChatClient.create_chat_message": "chat send",
    "ChatClient.get_suggested": "chat suggested",
    "ChatClient.stop_message": "chat stop",
    "ChatClient.get_conversations": "chat conversations",
    "ChatClient.get_conversation_messages": "chat messages",
    "ChatClient.rename_conversation": "chat rename-conversation",
    "ChatClient.delete_conversation": "chat delete-conversation",
    "ChatClient.audio_to_text": "audio-to-text",
    "ChatClient.annotation_reply_action": "chat annotation-reply-action",
    "ChatClient.get_annotation_reply_status": "chat annotation-reply-status",
    "ChatClient.list_annotations": "chat annotations list",
    "ChatClient.create_annotation": "chat annotations create",
    "ChatClient.update_annotation": "chat annotations update",
    "ChatClient.delete_annotation": "chat annotations delete",
    "ChatClient.get_conversation_variables": "chat variables list",
    "ChatClient.update_conversation_variable": "chat variables update",
    "ChatClient.delete_annotation_with_response": "chat annotations delete",
    "ChatClient.list_conversation_variables_with_pagination": "chat variables list",
    "ChatClient.update_conversation_variable_with_response": "chat variables update",
    "ChatClient.get_annotation_reply_job_status": "chat annotation-reply-status",
    "ChatClient.list_annotations_with_pagination": "chat annotations list",
    "ChatClient.create_annotation_with_response": "chat annotations create",
    "ChatClient.update_annotation_with_response": "chat annotations update",
    "WorkflowClient.run": "workflow run",
    "WorkflowClient.stop": "workflow stop",
    "WorkflowClient.get_result": "workflow result",
    "WorkflowClient.get_workflow_logs": "workflow logs",
    "WorkflowClient.run_specific_workflow": "workflow run-specific",
    "WorkflowClient.get_workflow_draft": "workflow draft get",
    "WorkflowClient.update_workflow_draft": "workflow draft update",
    "WorkflowClient.publish_workflow": "workflow publish",
    "WorkflowClient.get_workflow_run_history": "workflow history",
    "WorkspaceClient.get_available_models": "workspace models",
    "WorkspaceClient.get_available_models_by_type": "workspace models",
    "WorkspaceClient.get_model_providers": "workspace providers",
    "WorkspaceClient.get_model_provider_models": "workspace provider-models",
    "WorkspaceClient.validate_model_provider_credentials": (
        "workspace validate-credentials"
    ),
    "WorkspaceClient.get_file_info": "workspace file-info",
    "WorkspaceClient.get_file_download_url": "workspace file-download-url",
    "WorkspaceClient.delete_file": "workspace file-delete",
    "KnowledgeBaseClient.create_dataset": "kb dataset create",
    "KnowledgeBaseClient.list_datasets": "kb dataset list",
    "KnowledgeBaseClient.create_document_by_text": "kb document create-text",
    "KnowledgeBaseClient.update_document_by_text": "kb document update-text",
    "KnowledgeBaseClient.create_document_by_file": "kb document create-file",
    "KnowledgeBaseClient.update_document_by_file": "kb document update-file",
    "KnowledgeBaseClient.batch_indexing_status": "kb document indexing-status",
    "KnowledgeBaseClient.delete_dataset": "kb dataset delete",
    "KnowledgeBaseClient.delete_document": "kb document delete",
    "KnowledgeBaseClient.list_documents": "kb document list",
    "KnowledgeBaseClient.add_segments": "kb segment add",
    "KnowledgeBaseClient.query_segments": "kb segment query",
    "KnowledgeBaseClient.delete_document_segment": "kb segment delete",
    "KnowledgeBaseClient.update_document_segment": "kb segment update",
    "KnowledgeBaseClient.hit_testing": "kb metadata hit-test",
    "KnowledgeBaseClient.get_dataset_metadata": "kb metadata get",
    "KnowledgeBaseClient.create_dataset_metadata": "kb metadata create",
    "KnowledgeBaseClient.update_dataset_metadata": "kb metadata update",
    "KnowledgeBaseClient.get_built_in_metadata": "kb metadata built-in-get",
    "KnowledgeBaseClient.manage_built_in_metadata": "kb metadata built-in-manage",
    "KnowledgeBaseClient.update_documents_metadata": "kb metadata update-documents",
    "KnowledgeBaseClient.list_dataset_tags": "kb tag list-all",
    "KnowledgeBaseClient.bind_dataset_tags": "kb tag bind",
    "KnowledgeBaseClient.unbind_dataset_tag": "kb tag unbind",
    "KnowledgeBaseClient.get_dataset_tags": "kb tag list",
    "KnowledgeBaseClient.get_datasource_plugins": "kb pipeline datasource-plugins",
    "KnowledgeBaseClient.run_datasource_node": "kb pipeline run-datasource-node",
    "KnowledgeBaseClient.run_rag_pipeline": "kb pipeline run",
    "KnowledgeBaseClient.upload_pipeline_file": "kb pipeline upload-file",
    "KnowledgeBaseClient.get_dataset": "kb dataset get",
    "KnowledgeBaseClient.update_dataset": "kb dataset update",
    "KnowledgeBaseClient.batch_update_document_status": (
        "kb dataset batch-document-status"
    ),
    "KnowledgeBaseClient.create_dataset_from_template": (
        "kb dataset create-from-template"
    ),
    "KnowledgeBaseClient.duplicate_dataset": "kb dataset duplicate",
    "KnowledgeBaseClient.list_conversation_variables_with_pagination": (
        "chat variables list"
    ),
    "KnowledgeBaseClient.update_conversation_variable_with_response": (
        "chat variables update"
    ),
}
